//! Task entity per `docs/02-domain/tasks.md`.

use crate::common::{Energy, NoteBody};
use crate::validation::{validate_title, ValidationError, MAX_TASK_TITLE_LEN};
use jiff::Timestamp;
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use sunrise_id::EntityRef;

/// User-visible Task state. `done` and `cancelled` are NOT terminal: a task
/// can transition back to `todo`. `blocked` is **derived** at read time from
/// `blocked_by` and the blockers' states; it is NOT persisted.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TaskState {
    /// Pending; not yet started.
    Todo,
    /// Started but not yet complete.
    InProgress,
    /// Done. Not terminal — may transition back.
    Done,
    /// User explicitly cancelled. Not terminal.
    Cancelled,
}

impl TaskState {
    /// Allowed self-set transitions. (Note: `blocked` is derived, not
    /// persisted; it does not appear here.)
    #[must_use]
    pub fn can_transition_to(self, next: Self) -> bool {
        // todo ↔ in_progress, todo ↔ cancelled, in_progress ↔ done,
        // done → todo (resurrect), cancelled → todo. Same-state is a no-op.
        if self == next {
            return true;
        }
        matches!(
            (self, next),
            (Self::Todo, Self::InProgress | Self::Cancelled | Self::Done)
                | (Self::InProgress, Self::Todo | Self::Done | Self::Cancelled)
                | (Self::Done | Self::Cancelled, Self::Todo | Self::InProgress)
        )
    }
}

/// Persisted Task.
///
/// CRDT mapping (per spec): scalars → LWW-register; `contexts`, `blocks`,
/// `blocked_by` → OR-Sets; `deferred_count` → PN-counter; `body` → CRDT
/// RichText. `blocks_others` is **derived**, not persisted.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Task {
    /// Unique id (typed reference).
    pub id: EntityRef,
    /// Creation time.
    pub created_at: Timestamp,
    /// Last-update time (CRDT-derived: max of contributing op times).
    pub updated_at: Timestamp,
    /// Title; non-empty after trim, ≤ 512 chars.
    pub title: String,
    /// Optional body (rich text).
    #[serde(default)]
    pub body: Option<NoteBody>,
    /// Owning Stream (Inbox if unassigned).
    pub stream_id: EntityRef,
    /// Tag set (OR-Set semantics on the wire).
    #[serde(default)]
    pub contexts: BTreeSet<EntityRef>,
    /// User-set state (`blocked` is derived at read time, never stored here).
    pub state: TaskState,
    /// Optional priority 1..=5.
    #[serde(default)]
    pub priority: Option<u8>,
    /// Optional energy facet.
    #[serde(default)]
    pub energy: Option<Energy>,
    /// Optional ISO-8601 duration in seconds (we store seconds rather than
    /// the ISO string to keep CBOR canonical).
    #[serde(default)]
    pub estimated_duration_s: Option<u64>,
    /// When the user intends to do it.
    #[serde(default)]
    pub scheduled_at: Option<Timestamp>,
    /// Hard deadline.
    #[serde(default)]
    pub due_at: Option<Timestamp>,
    /// Set on transition to Done.
    #[serde(default)]
    pub completed_at: Option<Timestamp>,
    /// PN-counter; system-incremented on defer.
    #[serde(default)]
    pub deferred_count: i64,
    /// Block ids scheduling this task (OR-Set).
    #[serde(default)]
    pub blocks: BTreeSet<EntityRef>,
    /// Tasks this task depends on (OR-Set).
    #[serde(default)]
    pub blocked_by: BTreeSet<EntityRef>,
    /// Optional Person ref (informational only in v1; no delegation).
    #[serde(default)]
    pub assignee: Option<EntityRef>,
    /// If generated by a routine.
    #[serde(default)]
    pub routine_id: Option<EntityRef>,
    /// Occurrence date for routine-generated tasks.
    #[serde(default)]
    pub routine_occurrence: Option<Timestamp>,
    /// Archived (out of default views).
    #[serde(default)]
    pub archived: bool,
    /// Deleted (tombstone until compaction).
    #[serde(default)]
    pub deleted: bool,
}

/// Draft used by the UI when creating a Task. Only required fields appear;
/// the core fills timestamps, id, and defaults.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TaskDraft {
    /// Title (will be trimmed and validated).
    pub title: String,
    /// Optional body.
    pub body: Option<NoteBody>,
    /// Owning Stream; defaults to Inbox if `None`.
    pub stream_id: Option<EntityRef>,
    /// Optional contexts.
    pub contexts: Vec<EntityRef>,
    /// Optional priority 1..=5.
    pub priority: Option<u8>,
    /// Optional energy facet.
    pub energy: Option<Energy>,
    /// Optional estimated duration in seconds.
    pub estimated_duration_s: Option<u64>,
    /// Optional scheduled_at.
    pub scheduled_at: Option<Timestamp>,
    /// Optional due_at.
    pub due_at: Option<Timestamp>,
    /// Optional assignee.
    pub assignee: Option<EntityRef>,
}

/// Patch applied via `Command::UpdateTask`. `Some(None)` clears an optional
/// field; `None` leaves it unchanged.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TaskPatch {
    /// New title (if provided).
    pub title: Option<String>,
    /// Update body; outer `Option` chooses presence-of-update, inner is the
    /// new value (None to clear).
    pub body: Option<Option<NoteBody>>,
    /// Move to a new Stream.
    pub stream_id: Option<EntityRef>,
    /// Replace contexts (set semantics on apply).
    pub contexts: Option<Vec<EntityRef>>,
    /// New state.
    pub state: Option<TaskState>,
    /// New priority.
    pub priority: Option<Option<u8>>,
    /// New energy.
    pub energy: Option<Option<Energy>>,
    /// New duration.
    pub estimated_duration_s: Option<Option<u64>>,
    /// New scheduled_at.
    pub scheduled_at: Option<Option<Timestamp>>,
    /// New due_at.
    pub due_at: Option<Option<Timestamp>>,
    /// New blocked_by set (replaces).
    pub blocked_by: Option<Vec<EntityRef>>,
    /// New assignee.
    pub assignee: Option<Option<EntityRef>>,
    /// Archive or unarchive.
    pub archived: Option<bool>,
}

impl TaskDraft {
    /// Validate the draft against domain rules.
    ///
    /// Does NOT enforce the 1.25 MiB envelope cap (that's done in the core
    /// after CRDT encoding) or `blocked_by` cycles (done at submit time
    /// once the full graph is known).
    pub fn validate(&self) -> Result<(), ValidationError> {
        let _ = validate_title(&self.title, "task.title", MAX_TASK_TITLE_LEN)?;
        if let (Some(s), Some(d)) = (self.scheduled_at, self.due_at) {
            if d < s {
                return Err(ValidationError::DueBeforeScheduled);
            }
        }
        if let Some(p) = self.priority {
            if !(1..=5).contains(&p) {
                return Err(ValidationError::Field {
                    field: "task.priority",
                    constraint: "range_1_5",
                });
            }
        }
        Ok(())
    }
}

impl TaskPatch {
    /// Validate the patch's individual fields.
    pub fn validate(&self) -> Result<(), ValidationError> {
        if let Some(t) = &self.title {
            let _ = validate_title(t, "task.title", MAX_TASK_TITLE_LEN)?;
        }
        if let Some(Some(p)) = self.priority {
            if !(1..=5).contains(&p) {
                return Err(ValidationError::Field {
                    field: "task.priority",
                    constraint: "range_1_5",
                });
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use sunrise_id::{EntityKind, EntityRef};

    fn ref_t() -> EntityRef {
        EntityRef::new(EntityKind::Stream, [1u8; 16])
    }

    #[test]
    fn task_state_transitions() {
        assert!(TaskState::Todo.can_transition_to(TaskState::InProgress));
        assert!(TaskState::InProgress.can_transition_to(TaskState::Done));
        assert!(TaskState::Done.can_transition_to(TaskState::Todo));
        assert!(TaskState::Cancelled.can_transition_to(TaskState::Todo));
    }

    #[test]
    fn draft_validates_title() {
        let mut d = TaskDraft {
            title: "  do the thing  ".into(),
            stream_id: Some(ref_t()),
            ..Default::default()
        };
        d.validate().unwrap();
        d.title = String::new();
        assert_eq!(d.validate(), Err(ValidationError::InvalidTitle));
    }

    #[test]
    fn draft_rejects_due_before_scheduled() {
        let now = Timestamp::from_millisecond(1_700_000_000_000).unwrap();
        let later = now + jiff::SignedDuration::from_hours(1);
        let d = TaskDraft {
            title: "x".into(),
            scheduled_at: Some(later),
            due_at: Some(now),
            ..Default::default()
        };
        assert_eq!(d.validate(), Err(ValidationError::DueBeforeScheduled));
    }

    #[test]
    fn draft_rejects_priority_out_of_range() {
        let d = TaskDraft {
            title: "x".into(),
            priority: Some(6),
            ..Default::default()
        };
        assert!(matches!(
            d.validate(),
            Err(ValidationError::Field {
                constraint: "range_1_5",
                ..
            })
        ));
    }
}
