//! Wire-compatibility test: the pre-migration (chrono-era) canonical CBOR
//! fixtures MUST still decode into the post-migration (jiff-based) domain
//! types with value identity, and re-encode round-trips stably under jiff.
//!
//! The fixtures in `tests/fixtures/*.cbor` were generated by the chrono-based
//! `Serialize` impls before the jiff migration (see the ADR
//! `docs/11-adr/0011-datetime-jiff.md`). chrono and jiff both serialize a UTC
//! instant as the same RFC 3339 string (`2025-11-08T09:30:00.123Z`), so the
//! values survive exactly.
//!
//! They no longer re-encode to their own bytes, for two deliberate reasons:
//! `encode_canonical` now sorts map keys per RFC 8949 §4.2.1 (the fixtures were
//! written in declaration order, which was never canonical), and
//! `DOC_SCHEMA_V = 2` re-typed the Task time fields to `SunriseTime`. Byte
//! identity was always a bonus; the contract these tests enforce is *value*
//! identity — an older payload still decodes into the current types with the
//! same meaning.

use jiff::Timestamp;
use std::collections::BTreeSet;
use std::path::PathBuf;
use sunrise_cbor::{decode_canonical, decode_lenient, encode_canonical};
use sunrise_domain::common::{Energy, NoteBody};
use sunrise_domain::routine::{Routine, RoutineCatchupPolicy, TaskTemplate};
use sunrise_domain::rrule::{Frequency, RRule, Weekday};
use sunrise_domain::task::{Task, TaskState};
use sunrise_domain::{SunriseTime, Unknowns};
use sunrise_id::{EntityKind, EntityRef};

// Same ms constants used to generate the chrono-era fixtures.
const T_CREATED: i64 = 1_762_594_200_123;
const T_UPDATED: i64 = 1_762_597_800_456;
const T_SCHEDULED: i64 = 1_762_680_600_789;
const T_DUE: i64 = 1_762_767_000_111;
const T_COMPLETED: i64 = 1_762_600_000_222;
const T_ROUTINE_OCC: i64 = 1_762_594_500_333;

const R_CREATED: i64 = 1_762_594_200_123;
const R_UPDATED: i64 = 1_762_597_800_456;
const R_STARTS: i64 = 1_762_680_600_789;
const R_ENDS: i64 = 1_763_680_600_555;
const R_UNTIL: i64 = 1_764_680_600_444;
const R_SKIP1: i64 = 1_762_680_600_789;
const R_SKIP2: i64 = 1_762_767_000_111;
const R_LAST_COMPLETED: i64 = 1_762_600_000_222;
const R_PAUSED_UNTIL: i64 = 1_762_900_000_777;

fn ts(ms: i64) -> Timestamp {
    Timestamp::from_millisecond(ms).unwrap()
}

fn eref(kind: EntityKind, b: u8) -> EntityRef {
    EntityRef::new(kind, [b; 16])
}

fn expected_task() -> Task {
    let mut contexts = BTreeSet::new();
    contexts.insert(eref(EntityKind::Context, 0x33));
    contexts.insert(eref(EntityKind::Context, 0x34));
    let mut blocks = BTreeSet::new();
    blocks.insert(eref(EntityKind::Block, 0x44));
    let mut blocked_by = BTreeSet::new();
    blocked_by.insert(eref(EntityKind::Task, 0x55));
    Task {
        id: eref(EntityKind::Task, 0x11),
        created_at: ts(T_CREATED),
        updated_at: ts(T_UPDATED),
        title: "Ship the jiff migration".to_string(),
        body: Some(NoteBody(vec![1, 2, 3, 4])),
        stream_id: eref(EntityKind::Stream, 0x22),
        contexts,
        state: TaskState::InProgress,
        priority: Some(3),
        energy: Some(Energy::High),
        estimated_duration_s: Some(5400),
        scheduled_at: Some(ts(T_SCHEDULED).into()),
        due_at: Some(ts(T_DUE).into()),
        // New field defaults to empty and is skipped on the wire, so the
        // chrono-era fixtures still decode and re-encode byte-identically.
        scheduling_constraints: Vec::new(),
        completed_at: Some(ts(T_COMPLETED).into()),
        deferred_count: 2,
        blocks,
        blocked_by,
        assignee: Some(eref(EntityKind::Person, 0x66)),
        routine_id: Some(eref(EntityKind::Routine, 0x77)),
        routine_occurrence: Some(ts(T_ROUTINE_OCC)),
        archived: true,
        deleted: false,
        unknown: Unknowns::new(),
    }
}

fn expected_routine() -> Routine {
    Routine {
        id: eref(EntityKind::Routine, 0xA1),
        created_at: ts(R_CREATED),
        updated_at: ts(R_UPDATED),
        template: TaskTemplate {
            title: "Water the plants".to_string(),
            stream_id: eref(EntityKind::Stream, 0xA2),
            contexts: vec![eref(EntityKind::Context, 0xA3)],
            energy: Some(Energy::Low),
            priority: Some(2),
            estimated_duration_s: Some(600),
            body: Some(NoteBody(vec![9, 8, 7])),
        },
        rrule: RRule {
            freq: Frequency::Weekly,
            interval: 2,
            by_day: vec![Weekday::Mo, Weekday::We, Weekday::Fr],
            by_month_day: vec![-1, 15],
            by_month: vec![1, 6, 12],
            by_set_pos: vec![1, -1],
            count: Some(10),
            until: Some(ts(R_UNTIL)),
            wkst: Some(Weekday::Su),
        },
        timezone: "America/Los_Angeles".to_string(),
        starts_at: ts(R_STARTS),
        ends_at: Some(ts(R_ENDS)),
        scheduling_constraints: Vec::new(),
        skip_dates: vec![ts(R_SKIP1), ts(R_SKIP2)],
        // New field: defaults to empty and is skipped on the wire, so the
        // chrono-era fixture still decodes and re-encodes byte-identically.
        skipped_keys: Vec::new(),
        catchup_policy: RoutineCatchupPolicy::Merge,
        streak_counter: 7,
        last_completed_at: Some(ts(R_LAST_COMPLETED)),
        // Streak-mechanics fields: every one defaults to its "unset" value and
        // is skipped on the wire in that state, so the chrono-era fixture still
        // decodes and re-encodes byte-identically.
        grace_window_s: None,
        forgiveness_enabled: true,
        streak_started_at: None,
        forgivenesses_in_window: 0,
        streak_keys: Vec::new(),
        paused: true,
        paused_until: Some(ts(R_PAUSED_UNTIL)),
        archived: false,
        deleted: false,
        unknown: Unknowns::new(),
    }
}

fn fixture(name: &str) -> Vec<u8> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("read fixture {}: {e}", path.display()))
}

/// The Task fixture is NOT canonical any more, and that is the point.
///
/// `DOC_SCHEMA_V = 2` re-typed `scheduled_at` / `due_at` / `completed_at` from
/// a bare instant to a tagged [`SunriseTime`] (issue #6), so a v1 payload no
/// longer re-encodes to its own bytes. What must still hold — and what
/// `docs/10-cross-cutting/protocol-versioning.md` promises for a minor schema
/// change — is that the older payload still DECODES, with value identity, and
/// that each bare instant reads as an `Instant` and not as something else.
#[test]
fn chrono_task_fixture_decodes_under_jiff() {
    let bytes = fixture("task_chrono_v1.cbor");
    let task: Task = decode_lenient(&bytes).expect("v1 task payload decodes");

    let expected = expected_task();
    assert_eq!(task, expected, "full-value identity for Task");

    // ...and re-encoding it now produces the v2 shape, which round-trips
    // canonically from here on.
    let v2 = encode_canonical(&task).expect("re-encode at v2");
    let again: Task = decode_canonical(&v2).expect("v2 is canonical");
    assert_eq!(again, expected);

    // Explicit per-timestamp value checks (the migration's core claim).
    assert_eq!(
        task.created_at,
        Timestamp::from_millisecond(T_CREATED).unwrap()
    );
    assert_eq!(
        task.updated_at,
        Timestamp::from_millisecond(T_UPDATED).unwrap()
    );
    assert_eq!(
        task.scheduled_at,
        Some(SunriseTime::instant(
            Timestamp::from_millisecond(T_SCHEDULED).unwrap()
        )),
        "a v1 bare instant reads back as an Instant, not a floating time"
    );
    assert_eq!(
        task.due_at,
        Some(Timestamp::from_millisecond(T_DUE).unwrap().into())
    );
    assert_eq!(
        task.completed_at,
        Some(Timestamp::from_millisecond(T_COMPLETED).unwrap().into())
    );
    assert_eq!(
        task.routine_occurrence,
        Some(Timestamp::from_millisecond(T_ROUTINE_OCC).unwrap())
    );

    // The three re-typed fields are the ONLY thing that moved: everything
    // else in the v1 payload still re-encodes byte-identically. Asserted by
    // decoding the v2 re-encode and comparing values, plus checking that the
    // v1 bytes are no longer reproducible only because of those fields.
    assert_ne!(
        v2, bytes,
        "the tagged SunriseTime is a new encoding; if this matched, the kind \
         was not being written"
    );
}

/// The Routine fixture decodes with value identity, but no longer re-encodes
/// to its own bytes.
///
/// `encode_canonical` now sorts map keys by their encoded bytes, per RFC 8949
/// §4.2.1 and per what this repository's own docs have always said. The
/// chrono-era fixtures were written in struct DECLARATION order, which was
/// never canonical — the encoder just never enforced it. Value identity, which
/// is the contract the jiff migration actually needs, is unaffected.
#[test]
fn chrono_routine_fixture_decodes_under_jiff() {
    let bytes = fixture("routine_chrono_v1.cbor");
    let routine: Routine = decode_lenient(&bytes).expect("v1 routine payload decodes");

    let expected = expected_routine();
    assert_eq!(routine, expected, "full-value identity for Routine");

    assert_eq!(
        routine.starts_at,
        Timestamp::from_millisecond(R_STARTS).unwrap()
    );
    assert_eq!(
        routine.ends_at,
        Some(Timestamp::from_millisecond(R_ENDS).unwrap())
    );
    assert_eq!(
        routine.rrule.until,
        Some(Timestamp::from_millisecond(R_UNTIL).unwrap())
    );
    assert_eq!(
        routine.skip_dates,
        vec![
            Timestamp::from_millisecond(R_SKIP1).unwrap(),
            Timestamp::from_millisecond(R_SKIP2).unwrap()
        ]
    );
    assert_eq!(
        routine.last_completed_at,
        Some(Timestamp::from_millisecond(R_LAST_COMPLETED).unwrap())
    );
    assert_eq!(
        routine.paused_until,
        Some(Timestamp::from_millisecond(R_PAUSED_UNTIL).unwrap())
    );

    // Re-encoding produces the canonical (key-sorted) form, which then
    // round-trips exactly.
    let re = encode_canonical(&routine).unwrap();
    let back: Routine = decode_canonical(&re).unwrap();
    assert_eq!(back, expected);
}
