-- Sunrise local storage schema, migration to version 9: routine streak state.
-- Per the migrations doc: schema changes are always a NEW migration file,
-- never an edit of an existing one.
--
-- `routines.streak_counter` (0001) and `last_completed_at_ms` (0004) already
-- exist and are reused unchanged. The streak mechanics in
-- docs/08-features/recurrence-engine.md need four more pieces of per-Routine
-- state — the grace window, the forgiveness toggle and its consumed count, the
-- streak/forgiveness anchor, and the idempotency-key set. They are projected
-- into ONE canonical-CBOR blob column rather than five scalar columns:
-- the engine never queries them from SQL (they are read as a unit whenever a
-- Routine is materialized), and one blob keeps the routine row reader from
-- growing yet another positional argument.
--
-- NULL means "all defaults" — the state a routine that has never been
-- completed is in, and the state every pre-v9 row upgrades into.
--
-- The column is a projection: rebuildable from the op log, since the same
-- fields ride on the Routine entity inside every routine.create/update op.

ALTER TABLE routines ADD COLUMN streak_state BLOB;
