import AppIntents
import Foundation

/// How long a session should be, for the Shortcuts picker.
///
/// A mirror of the core's `SessionLength` rather than a reuse of it: that enum
/// is generated by UniFFI, and conforming a foreign type to `AppEnum` would
/// make this app's automation surface a thing the seam could break by
/// renaming. The mapping is three lines and the compiler checks it is total.
enum FocusLength: String, CaseIterable, AppEnum {
    case pomodoro
    case estimate
    case untilDone

    /// Catalog keys as literals; see the note on ``CaptureTaskIntent/title``.
    static let typeDisplayRepresentation = TypeDisplayRepresentation(
        name: LocalizedStringResource("apple.intents.focus_length.type_name", table: "Localizable")
    )

    static let caseDisplayRepresentations: [FocusLength: DisplayRepresentation] = [
        .pomodoro: DisplayRepresentation(
            title: LocalizedStringResource("apple.intents.focus_length.pomodoro", table: "Localizable")
        ),
        .estimate: DisplayRepresentation(
            title: LocalizedStringResource("apple.intents.focus_length.estimate", table: "Localizable")
        ),
        .untilDone: DisplayRepresentation(
            title: LocalizedStringResource("apple.intents.focus_length.until_done", table: "Localizable")
        )
    ]

    var sessionLength: SessionLength {
        switch self {
        case .pomodoro: .onePomodoro
        case .estimate: .sizedToEstimate
        case .untilDone: .untilDone
        }
    }
}

/// Start a focus session on a task.
///
/// Automating the *start* of a session is a statement, not an inference —
/// which is the line `focus-mode.md` §Auto-completion draws when it says
/// Sunrise infers nothing. Someone saying "start focusing on the report" has
/// declared what they are doing, exactly as pressing the button on the focus
/// screen does.
struct StartFocusIntent: AppIntent {
    /// Catalog keys as literals; see the note on ``CaptureTaskIntent/title``.
    static let title: LocalizedStringResource = LocalizedStringResource(
        "apple.intents.start_focus.title",
        table: "Localizable"
    )

    static let description = IntentDescription(
        LocalizedStringResource("apple.intents.start_focus.description", table: "Localizable"),
        categoryName: LocalizedStringResource("apple.intents.category_focus", table: "Localizable"),
        searchKeywords: ["focus", "pomodoro", "timer", "deep work"]
    )

    /// Runs without pulling Sunrise forward. Every one of these verbs is
    /// something you do *instead of* opening the app; a capture that stole
    /// focus would interrupt exactly the thought it exists to catch.
    static let supportedModes: IntentModes = .background

    static var parameterSummary: some ParameterSummary {
        Summary("Focus on \(\.$task) for \(\.$length)")
    }

    @Parameter(
        title: LocalizedStringResource("apple.intents.task_parameter", table: "Localizable"),
        requestValueDialog: IntentDialog(
            LocalizedStringResource("apple.intents.start_focus.task_prompt", table: "Localizable")
        )
    )
    var task: TaskEntity

    @Parameter(
        title: LocalizedStringResource("apple.intents.start_focus.length_title", table: "Localizable"),
        default: .pomodoro
    )
    var length: FocusLength

    init() {}

    init(task: TaskEntity, length: FocusLength) {
        self.task = task
        self.length = length
    }

    func perform() async throws -> some IntentResult & ProvidesDialog {
        let target = task.id
        let size = length
        let message = try await IntentVault.withVault { bridge in
            try await Self.start(on: target, length: size, in: bridge)
        }
        return .result(dialog: IntentDialog("\(message)"))
    }

    /// The whole of the work, with the vault passed in.
    static func start(
        on id: EntityRef,
        length: FocusLength,
        in bridge: CoreBridge
    ) async throws -> String {
        do {
            let item = try await TaskLookup.read(id, in: bridge)
            // The core will happily hold two open sessions; the focus screen
            // shows one. Rather than start a second one nothing can show, say
            // so — a timer the user cannot see is the silent failure this
            // whole surface exists to rule out.
            if let running = try await FocusSessions.running(in: bridge) {
                let name = await FocusSessions.title(of: running.start.taskId, in: bridge)
                throw IntentError.focusAlreadyRunning(name)
            }
            _ = try await bridge.submit(.startFocus(
                taskId: id,
                kind: .work,
                length: length.sessionLength,
                // Absent, so the core falls back to the task's own energy
                // facet. A budget invented here would be this surface holding
                // an opinion the user never expressed.
                energy: nil
            ))
            return L10n.Intents.StartFocus.started(
                title: item.title,
                length: sessionLengthLabel(length: length.sessionLength)
            )
        } catch {
            throw IntentError.wrapping(error)
        }
    }
}

/// Close the running focus session.
///
/// Its counterpart exists for a plain reason: a surface that can start a timer
/// and not stop it leaves an automation whose only undo is opening the app.
struct EndFocusIntent: AppIntent {
    /// Catalog keys as literals; see the note on ``CaptureTaskIntent/title``.
    static let title: LocalizedStringResource = LocalizedStringResource(
        "apple.intents.end_focus.title",
        table: "Localizable"
    )

    static let description = IntentDescription(
        LocalizedStringResource("apple.intents.end_focus.description", table: "Localizable"),
        categoryName: LocalizedStringResource("apple.intents.category_focus", table: "Localizable"),
        searchKeywords: ["focus", "stop", "end", "timer"]
    )

    /// Runs without pulling Sunrise forward. Every one of these verbs is
    /// something you do *instead of* opening the app; a capture that stole
    /// focus would interrupt exactly the thought it exists to catch.
    static let supportedModes: IntentModes = .background

    static var parameterSummary: some ParameterSummary {
        Summary("End the Sunrise focus session \(\.$completingTask)")
    }

    @Parameter(
        title: LocalizedStringResource("apple.intents.end_focus.complete_title", table: "Localizable"),
        default: false
    )
    var completingTask: Bool

    init() {}

    init(completingTask: Bool) {
        self.completingTask = completingTask
    }

    func perform() async throws -> some IntentResult & ProvidesDialog {
        let completing = completingTask
        let message = try await IntentVault.withVault { bridge in
            try await Self.end(completingTask: completing, in: bridge)
        }
        return .result(dialog: IntentDialog("\(message)"))
    }

    /// The whole of the work, with the vault passed in.
    static func end(completingTask: Bool, in bridge: CoreBridge) async throws -> String {
        do {
            guard let running = try await FocusSessions.running(in: bridge) else {
                throw IntentError.noFocusRunning
            }
            // `actualFocusedMs` is left absent deliberately: the core derives
            // the elapsed time from its own clock, and a number sent from here
            // would be this device's opinion of how long the session was.
            _ = try await bridge.submit(.endFocus(
                session: running.start.id,
                actualFocusedMs: nil,
                completedTask: completingTask
            ))
            let focused = durationClock(ms: running.focusedMs)
            guard completingTask else { return L10n.Intents.EndFocus.ended(duration: focused) }
            return L10n.Intents.EndFocus.endedCompleted(duration: focused)
        } catch {
            throw IntentError.wrapping(error)
        }
    }
}

/// The two reads both focus intents need.
enum FocusSessions {
    /// The newest session with no end, or `nil`.
    ///
    /// Newest rather than first, and only ever one, for the reason
    /// `FocusModel` gives: two running sessions is a state the core allows and
    /// a surface cannot render.
    static func running(in bridge: CoreBridge) async throws -> SessionRow? {
        guard case let .focusSessions(rows) = try await bridge.query(.runningFocusSessions) else {
            return nil
        }
        return rows.max { $0.start.startedAt < $1.start.startedAt }
    }

    /// A task's title, falling back to its id rather than to nothing.
    static func title(of id: EntityRef, in bridge: CoreBridge) async -> String {
        guard let item = try? await TaskLookup.read(id, in: bridge) else { return id }
        return item.title
    }
}
