//! The one `PairingPayload` the Apple unit tests hand the seam, kept honest by
//! the encoder that produces it.
//!
//! `apps/apple/SunriseTests/PairingFixture.swift` carries a base64 literal
//! because Swift has no constructor for a `PairingPayload` — one is built
//! inside the core, out of a vault, and a unit test has no vault. That literal
//! was written by hand and regenerated by hand, which is how it came to be
//! stale: #213 added fields 10 and 11 to the payload, the fixture kept the
//! nine-key shape, and `PairingModelTests` and `VaultSwitchingTests` failed on
//! CI rather than here.
//!
//! So both halves live here now. [`the_committed_apple_fixture_is_current`]
//! runs on every `cargo test` and fails the moment the CDDL moves;
//! [`regenerate_the_apple_pairing_fixture`] is `#[ignore]`d and rewrites the
//! Swift literal, on the same rule `sunrise-storage`'s vault fixtures follow —
//! a fixture is regenerated deliberately, through `mise run apple-pairing-fixture`,
//! and never as a side effect of running the suite.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::PathBuf;

use base64::engine::general_purpose::STANDARD;
use base64::Engine;
use sunrise_crypto::keys::{
    DeviceDhKeyPair, DeviceSigningKeyPair, IdentityDhKeyPair, IdentitySigningKeyPair,
};
use sunrise_crypto::{device_id_from_pub, identity_id_from_pub, DeviceCert, DeviceCertInner};
use sunrise_pairing::{encode_pairing_payload, PairingPayload};

/// `ID_S_priv` for the fixture. Public in the repository on purpose: this
/// payload seals nothing real, and a test that cannot be read is a test nobody
/// checks.
///
/// Since #105 it does **not** travel in the payload; it is here only because
/// the fixture's `device_cert` has to be signed by the account, which is what
/// a sponsor does with this key and a joiner never can.
const ID_S_PRIV: [u8; 32] = [0x11; 32];
/// The X25519 scalar behind the fixture's `ID_D_pub`. Never travels itself.
const ID_D_PRIV: [u8; 32] = [0x22; 32];
/// `D_S_priv` and `D_D_priv`: the device keys the *joiner* mints for its
/// `PairingRequest`, which the sponsor then writes into the cert.
const D_S_PRIV: [u8; 32] = [0x33; 32];
const D_D_PRIV: [u8; 32] = [0x44; 32];
/// The cert's `created_at_ms`. Fixed, because the fixture has to encode to the
/// same bytes on every run or the guard test below would fail by the clock.
const CERT_CREATED_AT_MS: u64 = 1_700_000_000_000;
/// The vault root inside the fixture, which `PairingFixture.vaultRoot` repeats
/// on the Swift side.
const VAULT_ROOT: [u8; 32] = [0xAB; 32];
/// One Stream key: the vault-meta stream, epoch 1.
const META_STREAM: [u8; 16] = [0u8; 16];
const META_KEY: [u8; 32] = [0xCD; 32];

/// The payload the Swift literal is the encoding of.
///
/// `genesis_*` equal the identity in force, which is what an account that has
/// never rotated looks like — and that is the account a fresh vault is.
///
/// Since #105 this is what a joiner *assembles* at the end of a three-message
/// exchange rather than what a sponsor sends: the account's public identity
/// from the offer, the device keys it minted itself for the request, and the
/// cert the sponsor issued over exactly those keys. Neither `ID_S_priv` nor
/// `ID_D_priv` is in it, which is the whole point, so `SunriseCore.open`
/// re-derives the cert's bindings and would refuse a fixture whose cert and
/// keys disagreed.
fn fixture_payload() -> PairingPayload {
    let signing = IdentitySigningKeyPair::from_secret_bytes(&ID_S_PRIV);
    let id_s_pub = signing.public_bytes();
    let d_s = DeviceSigningKeyPair::from_secret_bytes(&D_S_PRIV);
    let d_d = DeviceDhKeyPair::from_secret_bytes(D_D_PRIV);
    let mut stream_keys = BTreeMap::new();
    let mut per_epoch = BTreeMap::new();
    per_epoch.insert(1u32, META_KEY);
    stream_keys.insert(META_STREAM, per_epoch);
    let body = DeviceCertInner {
        v: 1,
        device_id: device_id_from_pub(&d_s.public_bytes()),
        d_s_pub: d_s.public_bytes(),
        d_d_pub: d_d.public_bytes(),
        identity_id: identity_id_from_pub(&id_s_pub),
        created_at_ms: CERT_CREATED_AT_MS,
        nickname: "fixture".into(),
        platform: "test".into(),
    };
    PairingPayload {
        id_s_pub,
        id_d_pub: IdentityDhKeyPair::from_secret_bytes(ID_D_PRIV).public_bytes(),
        identity_id: identity_id_from_pub(&id_s_pub),
        genesis_identity_id: identity_id_from_pub(&id_s_pub),
        genesis_id_s_pub: id_s_pub,
        d_s_priv: d_s.secret_bytes(),
        d_d_priv: d_d.secret_bytes(),
        device_cert: DeviceCert::issue(body, &signing)
            .expect("issue the fixture's device cert")
            .to_cbor()
            .expect("encode the fixture's device cert"),
        vault_root: VAULT_ROOT,
        stream_keys,
    }
}

fn swift_fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../apps/apple/SunriseTests/PairingFixture.swift")
}

/// The base64 the Swift file currently declares, read out of the source rather
/// than duplicated here — duplicating it would make this test agree with itself.
fn committed_base64() -> String {
    let src = std::fs::read_to_string(swift_fixture_path()).expect("read PairingFixture.swift");
    let (_, after) = src
        .split_once("static let base64 =")
        .expect("PairingFixture.swift declares `static let base64`");
    let (decl, _) = after
        .split_once("\n\n")
        .expect("the literal is followed by a blank line");
    // The quoted segments only: `+` is both a base64 character and Swift's
    // concatenation operator, so filtering by alphabet would silently splice
    // the operators into the value.
    let mut out = String::new();
    let mut rest = decl;
    while let Some((_, after_open)) = rest.split_once('"') {
        let Some((segment, after_close)) = after_open.split_once('"') else {
            panic!("unterminated string literal in PairingFixture.swift");
        };
        out.push_str(segment);
        rest = after_close;
    }
    out
}

/// Wrap a base64 string into the Swift literal `PairingFixture` declares.
///
/// 72 characters a line, continued with `+`, which is what the committed file
/// already looks like and what `SwiftLint`'s line-length rule allows.
fn swift_literal(b64: &str) -> String {
    let chunks: Vec<String> = b64
        .as_bytes()
        .chunks(72)
        .map(|c| String::from_utf8_lossy(c).into_owned())
        .collect();
    let mut out = String::from("    static let base64 =\n");
    for (i, chunk) in chunks.iter().enumerate() {
        if i == 0 {
            let _ = writeln!(out, "        \"{chunk}\"");
        } else {
            let _ = writeln!(out, "            + \"{chunk}\"");
        }
    }
    out
}

/// The committed Swift literal still decodes to what this encoder produces.
///
/// This is the test that should have existed: the Apple suite's failure mode
/// for a stale fixture is four opaque assertion failures inside an `XCTest` run
/// on a macOS runner, and this one names the cause in a Rust test that takes
/// milliseconds.
#[test]
fn the_committed_apple_fixture_is_current() {
    let encoded = encode_pairing_payload(&fixture_payload()).expect("encode the fixture payload");
    let expected = STANDARD.encode(&encoded);
    assert_eq!(
        committed_base64(),
        expected,
        "apps/apple/SunriseTests/PairingFixture.swift is stale — the pairing payload's CDDL \
         has moved since it was written. Regenerate it with `mise run apple-pairing-fixture`; \
         leaving it stale fails the macOS and iOS XCTest jobs instead of this one."
    );
}

/// Rewrite the Swift literal from the encoder.
///
/// `#[ignore]`d: an ordinary `cargo test` must *read* the committed fixture,
/// never replace it. Run it through `mise run apple-pairing-fixture`.
#[test]
#[ignore = "rewrites the committed Swift fixture; run it through `mise run apple-pairing-fixture`"]
fn regenerate_the_apple_pairing_fixture() {
    let encoded = encode_pairing_payload(&fixture_payload()).expect("encode the fixture payload");
    let b64 = STANDARD.encode(&encoded);
    let path = swift_fixture_path();
    let src = std::fs::read_to_string(&path).expect("read PairingFixture.swift");
    let start = src
        .find("    static let base64 =")
        .expect("PairingFixture.swift declares `static let base64`");
    let end = src[start..]
        .find("\n\n")
        .map(|i| start + i + 1)
        .expect("the literal is followed by a blank line");
    let rewritten = format!("{}{}{}", &src[..start], swift_literal(&b64), &src[end..]);
    std::fs::write(&path, rewritten).expect("write PairingFixture.swift");
}
