/**
 * `generated/messages.ts`: the web and docs-site binding.
 *
 * The compiled messages are data, and the accessors are a typed tree over
 * them: `createMessages(navigator.languages).web.app.title()`. A key renamed
 * in the TOML is a type error at every call site, and an argument added to a
 * message is a type error at every call site that does not pass it — the two
 * failures a string-keyed `t("web.app.title")` would carry to runtime.
 */

import { type Catalog, keysFor, SOURCE_LOCALE } from "./catalog";
import type { ArgKind, Message, Part } from "./message";
import { camel, type Tree, tree } from "./names";

const BANNER = `// Generated by packages/sunrise-i18n/build.ts from i18n/*.toml. Do not edit.
// Regenerate with \`mise run i18n\`; \`mise run i18n-check\` fails while this is stale.
`;

function partLiteral(part: Part): string {
    switch (part.kind) {
        case "text":
            return `{ kind: "text", value: ${JSON.stringify(part.value)} }`;
        case "arg":
        case "number":
            return `{ kind: "${part.kind}", name: ${JSON.stringify(part.name)} }`;
        case "pound":
            return `{ kind: "pound" }`;
        case "plural":
            return `{ kind: "plural", name: ${JSON.stringify(part.name)}, arms: [${part.arms
                .map(
                    (arm) =>
                        `{ key: ${JSON.stringify(arm.key)}, parts: [${arm.parts.map(partLiteral).join(", ")}] }`,
                )
                .join(", ")}] }`;
    }
}

function messageLiteral(message: Message): string {
    return `[${message.map(partLiteral).join(", ")}]`;
}

/** The source text of a message, for the accessor's doc comment. */
export function sourceText(message: Message): string {
    return message.map(partText).join("");
}

function partText(part: Part): string {
    switch (part.kind) {
        case "text":
            return part.value;
        case "arg":
            return `{${part.name}}`;
        case "number":
            return `{${part.name}, number}`;
        case "pound":
            return "#";
        case "plural":
            return `{${part.name}, plural, ${part.arms
                .map((a) => `${a.key} {${sourceText(a.parts)}}`)
                .join(" ")}}`;
    }
}

function docComment(text: string, indent: string): string {
    const safe = text.replaceAll("*/", "*\\/");
    return `${indent}/** ${safe} */\n`;
}

function argType(kind: ArgKind): string {
    return kind === "integer" ? "number" : "string";
}

function emitTree(
    node: Tree,
    catalog: Catalog,
    depth: number,
    lines: string[],
): void {
    const indent = "    ".repeat(depth);
    const source = catalog.messages.get(SOURCE_LOCALE);
    for (const [leaf, key] of node.leaves) {
        const message = source?.get(key) ?? [];
        const args = catalog.args.get(key) ?? new Map<string, ArgKind>();
        lines.push(docComment(sourceText(message), indent).trimEnd());
        if (args.size === 0) {
            lines.push(
                `${indent}${camel(leaf)}: (): string => f(${JSON.stringify(key)}),`,
            );
        } else {
            const fields = [...args]
                .map(([name, kind]) => `readonly ${name}: ${argType(kind)}`)
                .join("; ");
            lines.push(
                `${indent}${camel(leaf)}: (args: { ${fields} }): string =>`,
                `${indent}    f(${JSON.stringify(key)}, args),`,
            );
        }
    }
    for (const [branch, child] of node.branches) {
        lines.push(`${indent}${camel(branch)}: {`);
        emitTree(child, catalog, depth + 1, lines);
        lines.push(`${indent}},`);
    }
}

/** Emit `generated/messages.ts`. */
export function emitTs(catalog: Catalog): string {
    const keys = keysFor(catalog, "ts");
    const data: string[] = [];
    for (const locale of catalog.locales) {
        const messages = catalog.messages.get(locale);
        const present = keys.filter((k) => messages?.has(k));
        if (present.length === 0 && locale !== SOURCE_LOCALE) {
            continue;
        }
        data.push(`    ${JSON.stringify(locale)}: {`);
        for (const key of present) {
            const message = messages?.get(key) ?? [];
            data.push(
                `        ${JSON.stringify(key)}: ${messageLiteral(message)},`,
            );
        }
        data.push("    },");
    }
    const carried = catalog.locales.filter(
        (l) =>
            l === SOURCE_LOCALE ||
            keys.some((k) => catalog.messages.get(l)?.has(k)),
    );
    const accessors: string[] = [];
    emitTree(tree(keys, 0), catalog, 2, accessors);

    return `${BANNER}
import {
    type Catalog,
    createFormatter,
    direction,
    negotiate,
} from "../src/runtime";

/** Every locale this binding carries, the source locale first. */
export const locales = ${JSON.stringify(carried)} as const;

/** The locale every message is written in first, and falls back to. */
export const sourceLocale = ${JSON.stringify(SOURCE_LOCALE)};

const catalog: Catalog = {
${data.join("\n")}
};

/**
 * The typed messages for the best catalog locale among \`requested\`, in the
 * requester's preference order — \`navigator.languages\` in a browser.
 */
export function createMessages(requested: readonly string[]) {
    const locale = negotiate(locales, requested, sourceLocale);
    const f = createFormatter(catalog, sourceLocale, locale);
    return {
        /** The catalog locale chosen, for \`<html lang>\`. */
        locale,
        /** Its writing direction, for \`<html dir>\`. */
        dir: direction(locale),
${accessors.join("\n")}
    };
}

/** The accessor tree \`createMessages\` returns. */
export type Messages = ReturnType<typeof createMessages>;
`;
}
