/**
 * The Apple binding: `generated/Localizable.xcstrings` and
 * `generated/Strings.swift`.
 *
 * The String Catalog carries the messages and Foundation does the formatting,
 * CLDR plural selection included, so a translated locale added to the TOML
 * becomes a localization Xcode compiles like any other. `Strings.swift` is the
 * typed front of it: `L10n.Devices.unwoundNotice(count: 3)` rather than a
 * string key, so a renamed or re-argumented message is a compile error in the
 * app instead of a key printed on screen.
 *
 * Format arguments are positional (`%1$@`, `%2$lld`) and numbered by the
 * *source* message's argument order in every locale, which is what lets a
 * translation reorder its arguments without the call site knowing.
 */

import { type Catalog, keysFor, SOURCE_LOCALE } from "./catalog";
import { sourceText } from "./emit-ts";
import type { ArgKind, Part } from "./message";
import { camel, pascal, swiftIdent, type Tree, tree } from "./names";

const BANNER = `// Generated by packages/sunrise-i18n/build.ts from i18n/*.toml. Do not edit.
// Regenerate with \`mise run i18n\`; \`mise run i18n-check\` fails while this is stale.
`;

/** `%` is the format escape in every string Foundation formats. */
function escapePercent(text: string): string {
    return text.replaceAll("%", "%%");
}

function specifier(kind: ArgKind): string {
    return kind === "integer" ? "lld" : "@";
}

interface Rendered {
    value: string;
    substitutions: Record<string, unknown>;
}

function render(
    parts: readonly Part[],
    positions: ReadonlyMap<string, [number, ArgKind]>,
    inArm: boolean,
): Rendered {
    let value = "";
    const substitutions: Record<string, unknown> = {};
    for (const part of parts) {
        switch (part.kind) {
            case "text":
                value += escapePercent(part.value);
                break;
            case "arg":
            case "number": {
                const [n, kind] = positions.get(part.name) ?? [0, "string"];
                value += `%${n}$${specifier(kind)}`;
                break;
            }
            case "pound":
                value += inArm ? "%arg" : "#";
                break;
            case "plural": {
                const [n] = positions.get(part.name) ?? [0, "integer"];
                value += `%#@${part.name}@`;
                const plural: Record<string, unknown> = {};
                for (const arm of part.arms) {
                    // A String Catalog's `zero` variation applies to 0 in
                    // every language, which is ICU's `=0`. The catalog loader
                    // refuses `=0` where CLDR already has `zero`, so the two
                    // never meet.
                    const key = arm.key === "=0" ? "zero" : arm.key;
                    plural[key] = {
                        stringUnit: {
                            state: "translated",
                            value: render(arm.parts, positions, true).value,
                        },
                    };
                }
                substitutions[part.name] = {
                    argNum: n,
                    formatSpecifier: "lld",
                    variations: { plural },
                };
                break;
            }
        }
    }
    return { value, substitutions };
}

/** Sort an object's keys, recursively, so the JSON is byte-stable. */
function sorted(value: unknown): unknown {
    if (Array.isArray(value)) {
        return value.map(sorted);
    }
    if (typeof value === "object" && value !== null) {
        return Object.fromEntries(
            Object.keys(value)
                .sort()
                .map((k) => [k, sorted((value as Record<string, unknown>)[k])]),
        );
    }
    return value;
}

function positionsOf(
    catalog: Catalog,
    key: string,
): Map<string, [number, ArgKind]> {
    const args = catalog.args.get(key) ?? new Map<string, ArgKind>();
    return new Map(
        [...args].map(([name, kind], i): [string, [number, ArgKind]] => [
            name,
            [i + 1, kind],
        ]),
    );
}

/** Emit `generated/Localizable.xcstrings`. */
export function emitXcstrings(catalog: Catalog): string {
    const strings: Record<string, unknown> = {};
    for (const key of keysFor(catalog, "swift")) {
        const positions = positionsOf(catalog, key);
        const localizations: Record<string, unknown> = {};
        for (const locale of catalog.locales) {
            const message = catalog.messages.get(locale)?.get(key);
            if (message === undefined) {
                continue;
            }
            const { value, substitutions } = render(message, positions, false);
            localizations[locale] = {
                stringUnit: { state: "translated", value },
                ...(Object.keys(substitutions).length > 0
                    ? { substitutions }
                    : {}),
            };
        }
        strings[key] = { extractionState: "manual", localizations };
    }
    const doc = sorted({
        sourceLanguage: SOURCE_LOCALE,
        strings,
        version: "1.0",
    });
    return `${JSON.stringify(doc, null, 2)}\n`;
}

function swiftType(kind: ArgKind): string {
    return kind === "integer" ? "Int" : "String";
}

function swiftString(text: string): string {
    return JSON.stringify(text);
}

function emitTree(
    node: Tree,
    catalog: Catalog,
    depth: number,
    lines: string[],
): void {
    const indent = "    ".repeat(depth);
    const source = catalog.messages.get(SOURCE_LOCALE);
    for (const [leaf, key] of node.leaves) {
        const text = sourceText(source?.get(key) ?? []);
        const args = [...(catalog.args.get(key) ?? new Map<string, ArgKind>())];
        lines.push(`${indent}/// ${text.replaceAll("\n", " ")}`);
        const name = swiftIdent(camel(leaf));
        if (args.length === 0) {
            lines.push(
                `${indent}static var ${name}: String { L10n.tr(${swiftString(key)}) }`,
            );
        } else {
            const params = args
                .map(
                    ([n, kind]) =>
                        `${swiftIdent(camel(n))}: ${swiftType(kind)}`,
                )
                .join(", ");
            const passed = args.map(([n]) => swiftIdent(camel(n))).join(", ");
            lines.push(
                `${indent}static func ${name}(${params}) -> String {`,
                `${indent}    L10n.tr(${swiftString(key)}, ${passed})`,
                `${indent}}`,
            );
        }
    }
    for (const [branch, child] of node.branches) {
        lines.push("", `${indent}enum ${swiftIdent(pascal(branch))} {`);
        emitTree(child, catalog, depth + 1, lines);
        lines.push(`${indent}}`);
    }
}

/**
 * Emit `generated/Strings.swift`.
 *
 * `apple.` is dropped from the Swift names — the app has no other surface to
 * tell it from — and `common.` stays as `L10n.Common`.
 */
export function emitSwift(catalog: Catalog): string {
    const keys = keysFor(catalog, "swift");
    const apple = keys.filter((k) => k.startsWith("apple."));
    const common = keys.filter((k) => k.startsWith("common."));
    const root = tree(apple, 1);
    if (common.length > 0) {
        if (root.branches.has("common") || root.leaves.has("common")) {
            throw new Error(
                "`apple.common` would collide with `common` in L10n; rename it",
            );
        }
        root.branches.set("common", tree(common, 1));
    }
    const lines: string[] = [];
    emitTree(root, catalog, 1, lines);
    return `${BANNER}
import Foundation

/// Every string in \`i18n/en.toml\` the Apple apps show, typed.
///
/// Each accessor reads \`Localizable.xcstrings\` from the main bundle, so the
/// user's language and its CLDR plural rules are Foundation's to apply.
enum L10n {
    /// Look \`key\` up and format it with \`args\` in the current locale.
    ///
    /// \`String(format:locale:arguments:)\` is what resolves a plural
    /// substitution: the looked-up format carries the variations with it.
    fileprivate static func tr(_ key: String, _ args: CVarArg...) -> String {
        let format = Bundle.main.localizedString(forKey: key, value: nil, table: "Localizable")
        return String(format: format, locale: Locale.current, arguments: args)
    }
${lines.join("\n")}
}
`;
}
