/**
 * `generated/strings.rs`: the CLI binding.
 *
 * An `include!`-ready file, as `tokens.rs` is (ADR-0029 §1): an inner doc
 * comment would be a hard error where it expands, so the banner is `//`
 * comments and every item carries an outer `///`. Each message compiles to a
 * function that builds its `String` directly — no catalog is parsed at run
 * time and no key can be misspelt at a call site.
 *
 * The including module supplies `rt`, the runtime every function calls:
 *
 * ```text
 * rt::locale() -> &'static str          the catalog locale in use
 * rt::plural(locale, i64) -> rt::Category   CLDR cardinal category
 * rt::number(locale, i64) -> String     the integer in the locale's digits
 * ```
 *
 * `crates/sunrise-cli/src/i18n.rs` is that module, backed by ICU4X.
 */

import { type Catalog, keysFor, SOURCE_LOCALE } from "./catalog";
import { sourceText } from "./emit-ts";
import type { ArgKind, Message, Part } from "./message";
import { pascal, rustIdent, type Tree, tree } from "./names";

const BANNER = `// Generated by packages/sunrise-i18n/build.ts from i18n/*.toml. Do not edit.
// Regenerate with \`mise run i18n\`; \`mise run i18n-check\` fails while this is stale.
//
// \`include!\`d by crates/sunrise-cli/src/i18n.rs, which supplies \`rt\`.
`;

function rustString(text: string): string {
    // JSON string escapes are a subset of Rust's, except `\\u{…}` spelling:
    // JSON writes `\\u0007`, Rust wants `\\u{7}`.
    return JSON.stringify(text).replace(
        /\\u([0-9a-fA-F]{4})/g,
        (_, hex: string) => `\\u{${hex}}`,
    );
}

function rustChar(c: string): string {
    // The string literal's escapes are valid in a char literal (`'\"'`
    // included); only a bare `'` needs one there that it does not in a string.
    const inner = rustString(c).slice(1, -1);
    return `'${inner === "'" ? "\\'" : inner}'`;
}

/** Whether `parts` call into `rt` — a plural, a `#`, or an integer argument. */
function usesRt(
    parts: readonly Part[],
    args: ReadonlyMap<string, ArgKind>,
): boolean {
    return parts.some(
        (p) =>
            p.kind === "plural" ||
            p.kind === "pound" ||
            p.kind === "number" ||
            (p.kind === "arg" && args.get(p.name) === "integer"),
    );
}

/** Whether any function at or under `node` calls into `rt`. */
function treeUsesRt(node: Tree, catalog: Catalog): boolean {
    for (const key of node.leaves.values()) {
        const args = catalog.args.get(key) ?? new Map<string, ArgKind>();
        for (const locale of catalog.locales) {
            const message = catalog.messages.get(locale)?.get(key);
            if (message === undefined) {
                continue;
            }
            // A key any other locale translates dispatches on `rt::locale()`.
            if (locale !== SOURCE_LOCALE || usesRt(message, args)) {
                return true;
            }
        }
    }
    return [...node.branches.values()].some((b) => treeUsesRt(b, catalog));
}

/**
 * The statements that append `parts` to `out`. `args` holds the message's
 * argument kinds, which decide whether a bare `{name}` is a `&str` pushed as
 * it is or an `i64` formatted in the locale's digits.
 */
function body(
    args: ReadonlyMap<string, ArgKind>,
    parts: readonly Part[],
    locale: string,
    indent: string,
    count: string | undefined,
): string[] {
    const lines: string[] = [];
    for (const part of parts) {
        switch (part.kind) {
            case "text":
                // `push` for one character: `push_str` of a one-character
                // literal is clippy's `single_char_add_str`, and the CLI
                // builds with warnings denied.
                lines.push(
                    [...part.value].length === 1
                        ? `${indent}out.push(${rustChar(part.value)});`
                        : `${indent}out.push_str(${rustString(part.value)});`,
                );
                break;
            case "arg":
            case "number":
                lines.push(
                    part.kind === "arg" && !isInteger(part.name)
                        ? `${indent}out.push_str(${rustIdent(part.name)});`
                        : `${indent}out.push_str(&rt::number(${rustString(locale)}, ${rustIdent(part.name)}));`,
                );
                break;
            case "pound":
                lines.push(
                    `${indent}out.push_str(&rt::number(${rustString(locale)}, ${count ?? "0"}));`,
                );
                break;
            case "plural": {
                const n = rustIdent(part.name);
                const exact = part.arms.find((a) => a.key === "=0");
                const categories = part.arms.filter(
                    (a) => a.key !== "=0" && a.key !== "other",
                );
                const other = part.arms.find((a) => a.key === "other");
                const inner = `${indent}        `;
                let prefix = `${indent}`;
                if (exact !== undefined) {
                    lines.push(`${indent}if ${n} == 0 {`);
                    lines.push(
                        ...body(args, exact.parts, locale, `${indent}    `, n),
                    );
                    lines.push(`${indent}} else {`);
                    prefix = `${indent}    `;
                }
                lines.push(
                    `${prefix}match rt::plural(${rustString(locale)}, ${n}) {`,
                );
                for (const arm of categories) {
                    lines.push(
                        `${prefix}    rt::Category::${pascal(arm.key)} => {`,
                    );
                    lines.push(
                        ...body(
                            args,
                            arm.parts,
                            locale,
                            exact === undefined ? inner : `${inner}    `,
                            n,
                        ),
                    );
                    lines.push(`${prefix}    }`);
                }
                lines.push(`${prefix}    _ => {`);
                lines.push(
                    ...body(
                        args,
                        other?.parts ?? [],
                        locale,
                        exact === undefined ? inner : `${inner}    `,
                        n,
                    ),
                );
                lines.push(`${prefix}    }`);
                lines.push(`${prefix}}`);
                if (exact !== undefined) {
                    lines.push(`${indent}}`);
                }
                break;
            }
        }
    }
    return lines;

    function isInteger(name: string): boolean {
        return args.get(name) === "integer";
    }
}

function rustType(kind: ArgKind): string {
    return kind === "integer" ? "i64" : "&str";
}

function emitFunction(
    catalog: Catalog,
    key: string,
    leaf: string,
    indent: string,
): string[] {
    const args = catalog.args.get(key) ?? new Map<string, ArgKind>();
    const params = [...args]
        .map(([name, kind]) => `${rustIdent(name)}: ${rustType(kind)}`)
        .join(", ");
    const source = catalog.messages.get(SOURCE_LOCALE)?.get(key) ?? [];
    const translated = catalog.locales
        .filter((l) => l !== SOURCE_LOCALE)
        .map((l): [string, Message | undefined] => [
            l,
            catalog.messages.get(l)?.get(key),
        ])
        .filter((entry): entry is [string, Message] => entry[1] !== undefined);
    const lines = [
        ...sourceText(source)
            .split("\n")
            .map((l) => `${indent}/// ${l}`.trimEnd()),
        `${indent}#[must_use]`,
        `${indent}pub fn ${rustIdent(leaf)}(${params}) -> String {`,
        `${indent}    let mut out = String::new();`,
    ];
    if (translated.length === 0) {
        lines.push(
            ...body(args, source, SOURCE_LOCALE, `${indent}    `, undefined),
        );
    } else {
        lines.push(`${indent}    match rt::locale() {`);
        for (const [locale, message] of translated) {
            lines.push(`${indent}        ${rustString(locale)} => {`);
            lines.push(
                ...body(
                    args,
                    message,
                    locale,
                    `${indent}            `,
                    undefined,
                ),
            );
            lines.push(`${indent}        }`);
        }
        lines.push(`${indent}        _ => {`);
        lines.push(
            ...body(
                args,
                source,
                SOURCE_LOCALE,
                `${indent}            `,
                undefined,
            ),
        );
        lines.push(`${indent}        }`, `${indent}    }`);
    }
    lines.push(`${indent}    out`, `${indent}}`);
    return lines;
}

function emitTree(
    node: Tree,
    catalog: Catalog,
    path: string[],
    lines: string[],
): void {
    const indent = "    ".repeat(path.length);
    for (const [leaf, key] of node.leaves) {
        lines.push(...emitFunction(catalog, key, leaf, indent));
        lines.push("");
    }
    for (const [branch, child] of node.branches) {
        lines.push(
            `${indent}/// \`${[...path, branch].join(".")}\` messages.`,
            `${indent}pub mod ${rustIdent(branch)} {`,
        );
        // Imported only where something at or below this module calls it,
        // since an unused import is a warning and the CLI denies warnings.
        if (treeUsesRt(child, catalog)) {
            lines.push(`${indent}    use super::rt;`, "");
        }
        emitTree(child, catalog, [...path, branch], lines);
        if (lines.at(-1) === "") {
            lines.pop();
        }
        lines.push(`${indent}}`, "");
    }
}

/**
 * Emit `generated/strings.rs`.
 *
 * `cli.` is dropped from the module path (`strings::devices::…`), and
 * `common.` stays as `strings::common`.
 */
export function emitRust(catalog: Catalog): string {
    const keys = keysFor(catalog, "rust");
    const cli = keys.filter((k) => k.startsWith("cli."));
    const common = keys.filter((k) => k.startsWith("common."));
    const root = tree(cli, 1);
    if (common.length > 0) {
        if (root.branches.has("common") || root.leaves.has("common")) {
            throw new Error(
                "`cli.common` would collide with `common` in strings.rs; rename it",
            );
        }
        root.branches.set("common", tree(common, 1));
    }
    const carried = catalog.locales.filter(
        (l) =>
            l === SOURCE_LOCALE ||
            keys.some((k) => catalog.messages.get(l)?.has(k)),
    );
    const lines: string[] = [];
    emitTree(root, catalog, [], lines);
    while (lines.at(-1) === "") {
        lines.pop();
    }
    return `${BANNER}
/// Every locale this binding carries, the source locale first.
pub const LOCALES: &[&str] = &[${carried.map(rustString).join(", ")}];

${lines.join("\n")}
`;
}
